name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use the Node.js version that matches your project

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.5.0 # Use the version specified in your packageManager field

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # The folder that contains your built static files
